# Generated by Django 3.0.5 on 2020-05-01 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlucoseUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('ratio_to_mmol_l', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bread_units_per_100g', models.FloatField()),
                ('glycemic_index', models.IntegerField()),
                ('fat_per_100g', models.IntegerField()),
                ('carbohydrate_per_100g', models.IntegerField()),
                ('protein_per_100g', models.IntegerField()),
                ('energy_kKkal_per_100g', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IngredientUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams_int_unit', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Insulin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='WeightUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('ratio_to_gramm', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('glucose_level', models.IntegerField(null=True)),
                ('insulin_amount', models.FloatField(null=True)),
                ('notes', models.CharField(max_length=32)),
                ('glucose_level_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.GlucoseUnit')),
                ('insulin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Insulin')),
            ],
        ),
        migrations.CreateModel(
            name='MealIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('ingredient_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.IngredientUnit')),
                ('ingredinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ingredient')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Record')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.WeightUnit'),
        ),
    ]
