# Generated by Django 3.0.5 on 2020-04-23 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='long_acting_insulin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='long', to='core.Insulin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rapid_acting_insulin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapid', to='core.Insulin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sugar_level_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.SugarLevelUnit'),
        ),
    ]
