# Generated by Django 3.0.5 on 2020-04-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insulinshot',
            name='amount_units',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='insulinshot',
            name='time',
            field=models.TimeField(default=0),
        ),
    ]
