# Generated by Django 3.0.5 on 2020-04-17 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200417_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insulinshot',
            name='amount_units',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='insulinshot',
            name='insulin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Insulin'),
        ),
        migrations.AlterField(
            model_name='insulinshot',
            name='time',
            field=models.TimeField(),
        ),
    ]
