# Generated by Django 3.0.5 on 2020-05-01 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200501_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='glucose_level_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.GlucoseUnit'),
        ),
        migrations.AddField(
            model_name='user',
            name='long_acting_insulin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='long', to='core.Insulin'),
        ),
        migrations.AddField(
            model_name='user',
            name='rapid_acting_insulin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapid', to='core.Insulin'),
        ),
    ]
