# Generated by Django 3.0.5 on 2020-04-16 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_insulinshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insulin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='insulinshot',
            name='insulin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Insulin'),
        ),
    ]
