# Generated by Django 3.0.5 on 2020-04-20 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200420_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='meal',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Meal'),
            preserve_default=False,
        ),
    ]
