# Generated by Django 3.0.5 on 2022-04-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220426_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_bread_units',
            field=models.BooleanField(default=False),
        ),
    ]
