# Generated by Django 3.0.5 on 2022-04-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_show_bread_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_calories_today',
            field=models.BooleanField(default=False),
        ),
    ]
