# Generated by Django 3.0.5 on 2020-05-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200501_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealingredient',
            name='record',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Record'),
        ),
    ]
