# Generated by Django 3.0.5 on 2020-04-24 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_unit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='activityPeriod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.ActivityPeriod'),
        ),
        migrations.AlterField(
            model_name='record',
            name='insulinShot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.InsulinShot'),
        ),
        migrations.AlterField(
            model_name='record',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Meal'),
        ),
        migrations.AlterField(
            model_name='record',
            name='notes',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='sugarLevel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.SugarLevel'),
        ),
    ]
