# Generated by Django 3.0.5 on 2020-05-01 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200501_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealingredient',
            old_name='ingredinet',
            new_name='ingredient',
        ),
    ]
