# Generated by Django 3.0.5 on 2020-04-28 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200426_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealingredient',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meal_ingredients', to='core.Meal'),
        ),
    ]
