# Generated by Django 3.0.5 on 2020-05-01 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200501_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientunit',
            old_name='grams_int_unit',
            new_name='grams_in_unit',
        ),
        migrations.RemoveField(
            model_name='weightunit',
            name='ratio_to_gramm',
        ),
    ]
