# Generated by Django 3.0.5 on 2020-05-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200501_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealingredient',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
