# Generated by Django 3.0.5 on 2020-04-28 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200428_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealingredient',
            old_name='indredient_unit',
            new_name='ingredient_unit',
        ),
    ]
