# Generated by Django 3.0.5 on 2020-05-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_record_bread_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
