# Generated by Django 3.0.5 on 2020-05-04 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200504_0759'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MealIngredient',
            new_name='Meal',
        ),
    ]
