# Generated by Django 3.0.5 on 2020-05-04 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200504_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientunit',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='ingredientunit',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='ingredient_unit',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='record',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='IngredientUnit',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='WeightUnit',
        ),
    ]
