# Generated by Django 3.0.5 on 2020-05-05 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(default=0)),
                ('glucose_level', models.IntegerField(default=0, null=True)),
                ('insulin_amount', models.FloatField(default=0, null=True)),
                ('bread_units', models.FloatField(default=0, null=True)),
                ('notes', models.CharField(max_length=256, null=True)),
                ('glucose_level_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.GlucoseUnit')),
                ('insulin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Insulin')),
            ],
        ),
    ]
