# Generated by Django 3.0.5 on 2020-05-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20200512_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='glucose_level',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='insulin_amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
