# Generated by Django 3.0.5 on 2021-04-08 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_auto_20200521_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField()),
                ('meal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='records.Meal')),
            ],
        ),
    ]
