# Generated by Django 3.0.5 on 2021-04-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_auto_20210408_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='data',
            field=models.TextField(),
        ),
    ]
