# Generated by Django 3.0.5 on 2021-05-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_photo_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumb',
            field=models.TextField(null=True),
        ),
    ]
