# Generated by Django 3.0.5 on 2021-05-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_auto_20210507_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumb',
            field=models.TextField(default=models.TextField()),
        ),
    ]
