# Generated by Django 3.0.5 on 2021-05-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_auto_20210507_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumb',
            field=models.TextField(),
        ),
    ]
