# Generated by Django 3.0.5 on 2021-05-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_auto_20210507_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='notes',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
