# Generated by Django 3.0.5 on 2022-04-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_auto_20210525_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='calories',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
