GET http://127.0.0.1:8000/api/ingredients/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjM0Mzc2MDI2LCJqdGkiOiI5NjU4N2JhMGE0YWY0MDkyOGE1Yjc5NWNlNjJiMTQ2ZSIsInVzZXJfaWQiOjN9.gCvUEfmLIpo7xArKx-50oOv1R4kv_UhEmmhhXkUIB3I