GET http://192.168.113.101:9000/api/ingredient/25/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjM0NTg1NDA3LCJqdGkiOiJiNGE3YjRjNGNlNmE0NDc3OWU2NDM1OTgwMTY0MWZmNiIsInVzZXJfaWQiOjJ9.JsqCpuTDJYYXh1KjvdRepEpNJnzpK-HE_cMAUXyN_Uo