GET http://localhost:8000/api/ingredient/46/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjM1MzQzMTUzLCJqdGkiOiIzN2JmNzBjMGM3ODk0ODRmOTUwZDE4MDc2YWFmYWEzMiIsInVzZXJfaWQiOjN9.f8E0j_6fnr_6VutWm-XSOmvoTDe9kZGR3YcBSNsn2Gk