POST http://192.168.113.101:9000/api/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjI5NDQ3MDgzLCJqdGkiOiIyNjE2ZGNmYjFjYzM0YTI1YmQ0YmVmMjIyNWZkZGIyOCIsInVzZXJfaWQiOjF9.ttLxJ9xldsJJyWNXKrjjulDO_XhpcP0-jD0f8FWvVTA

{
  "type":0,
  "time": "2021-05-13T15:15",
  "bread_units":1.5,
  "glucose_level":1.5, 
  "insulin_amount":1,
  "notes":"Not much"
}