GET https://type-one.herokuapp.com/api/records/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjMwNTc1MTcxLCJqdGkiOiJhZDYwMzFkOGJhNTA0MWQzYmVhYmNlZWZhOTE4ZDRiMyIsInVzZXJfaWQiOjd9.d7GPGnRLxUbfHO31olZ7079YeQ9E-rt1v3pMMdxo6p4