GET http://192.168.0.191:8000/api/records/ HTTP/1.1
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjM0Mzc1ODA5LCJqdGkiOiI5N2Y0YmFmZTVlY2I0MGYxYTI4ODA3YzkwNThhNTAyYyIsInVzZXJfaWQiOjd9.aBNWZijB7LzzPXZY55gIuciUyaskfHCwRxWVNyRJ65s