# Generated by Django 3.0.5 on 2020-05-04 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0014_auto_20200504_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bread_units_per_100g', models.FloatField()),
                ('glycemic_index', models.IntegerField()),
                ('fat_per_100g', models.IntegerField()),
                ('carbohydrate_per_100g', models.IntegerField()),
                ('protein_per_100g', models.IntegerField()),
                ('energy_kKkal_per_100g', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IngredientUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams_in_unit', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='meal.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='WeightUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.Ingredient')),
                ('ingredient_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal.IngredientUnit')),
                ('record', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Record')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='meal.WeightUnit'),
        ),
    ]
