# Generated by Django 3.0.5 on 2020-05-05 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bread_units_per_100g', models.FloatField()),
                ('glycemic_index', models.IntegerField()),
                ('fat_per_100g', models.IntegerField()),
                ('carbohydrate_per_100g', models.IntegerField()),
                ('protein_per_100g', models.IntegerField()),
                ('energy_kKkal_per_100g', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeightUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams_in_unit', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ingredients.Ingredient')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ingredients.WeightUnit')),
            ],
        ),
    ]
