# Generated by Django 3.0.5 on 2020-05-11 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_auto_20200510_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientunit',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.Ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredientunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.WeightUnit'),
        ),
    ]
