# Generated by Django 3.0.5 on 2021-07-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0006_ingredienthint'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredienthint',
            name='thumb',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
