# Generated by Django 3.0.5 on 2022-04-26 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0008_ingredienthint_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienthint',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='ingredients.Ingredient'),
        ),
    ]
