# Generated by Django 3.1.14 on 2022-05-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0009_auto_20220426_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('search_pattern', models.CharField(max_length=64)),
                ('select_pattern', models.CharField(max_length=64)),
            ],
        ),
    ]
