# Generated by Django 3.1.14 on 2022-05-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0010_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='search_pattern',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='source',
            name='select_pattern',
            field=models.CharField(max_length=128),
        ),
    ]
