#import pwd
# Generated by Django 3.1.14 on 2022-05-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0011_auto_20220504_1529'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbohydrate_per_100g',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat_per_100g',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein_per_100g',
            field=models.FloatField(),
        ),
    ]
